stages:
  - build
  - test

build:
  stage: build
  image: docker:latest
  variables:
    DOCKER_TLS_CERTDIR: ""  # Disable TLS for Docker-in-Docker
    DOCKER_HOST: "tcp://docker:2375"  # Connect to the Docker daemon provided by docker:dind
  services:
    - docker:dind
  script:
    - echo "Starting the build process"
    - docker --version
    - docker compose build
  only:
    - project

# Test stage
test:
 stage: test
  script:
   - echo "Running tests"
   - docker compose up -d
   # - docker compose exec <service-name> npm test  # Replace with your test command
   - docker compose down
  only:
   - project
