stages:
  - test

test_job:
  stage: test
  image: docker:latest
  script:
    - echo "Hello, GitLab CI/CD!"
    - uname -a
    - docker --version   # Check Docker version to verify Docker is accessible
