upstream backend {
    server service1:8199;
}

server {
    listen 80;

    resolver 127.0.0.11 valid=5s; # Docker DNS resolver to resolve services' IP addresses
    
    include /etc/nginx/mime.types;
    
    auth_basic "Restricted Content";
    auth_basic_user_file /etc/nginx/.htpasswd;

    location / {
        root /usr/share/nginx/html;
        index index.html;

    }

    location /api {
        proxy_pass http://backend/;
    }

    location /api/stop {
        proxy_pass http://controller:5000/stop;
    }
}