#load_module modules/ngx_http_api_module.so;

upstream backend {
    server api_gateway:80; 
}

server {
    listen 80;

    resolver 127.0.0.11 valid=5s; # Docker DNS resolver to resolve services' IP addresses
    
    include /etc/nginx/mime.types;
    
    auth_basic "Authentication Reset Required"; # For Basic Auth
    auth_basic_user_file /etc/nginx/.htpasswd; # Password file location for Basic Auth

    location / { # Route the user to the frontend: index.html file within this container
        root /usr/share/nginx/html;
        index index.html;
    }


    location /api/stop { # Controller service to kill all the containers
        proxy_pass http://controller:5000/stop;
    }
    
    location /api/ { # When "REQUEST" button is pressed in the frontend, the request is sent to the backend service
        proxy_pass http://api_gateway/;
    }
}